### ISSUE TITLE
isFileValid has bogus code.

### ISSUE THREAD

**Issue by Danack** [froala/wysiwyg-editor-php-sdk#16]
The code on these [lines](https://github.com/froala/wysiwyg-editor-php-sdk/blob/749aca2d5ca0fdb821130da60dbe671aeef06a75/lib/FroalaEditor/Utils/Utils.php#L22-L25) has multiple severe issues.

== Problem 1

```
    $extension = end($filename);
```
The [end function](http://php.net/manual/en/function.end.php) expects an array as input, not a string. This code emits a warning on my machine. Whoever wrote it, presumably has warnings disabled on their machine, which is a terrible idea.

== Problem 2

Almost any use of in_array should set the 3rd parameter to true, to enforce a comparison of the exact type, because otherwise, this can happen:

```
$allowedExts = [true];

var_dump(in_array('png', $allowedExts));
```
Which is 'surprising'.

**Comment by NunoLopes96** [comment]
In the Problem 1:
The error it is on the function document:
https://github.com/froala/wysiwyg-editor-php-sdk/blob/749aca2d5ca0fdb821130da60dbe671aeef06a75/lib/FroalaEditor/Utils/Utils.php#L9

it should be type array since it is really an array:
https://github.com/froala/wysiwyg-editor-php-sdk/blob/749aca2d5ca0fdb821130da60dbe671aeef06a75/lib/FroalaEditor/Utils/Utils.php#L58

**Comment by Danack** [comment]
ah, sorry. I was confused by the variable name.
